config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root :to => 'welcome#index'
	resources :events 
	resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
	
	validates :start_date, presence: true
  validate :future_event
	
private
  def future_event
   if start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
  end
	end
  
	validates :duration, presence: true,  numericality: { only_integer: true, greater_than: 0 }
	validates :title, presence: true, length: { in: 5..140 }
	validates :description, presence: true, length: { in: 20..1000 }
	validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000}
	validates :location, presence: true
	belongs_to :user
	has_many :attendances
	
	 def event_send
    EventMailer.event_email(self).deliver_now
  end
end
	

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :events
	has_many :attendances, through: :events
	after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user
	
	def new
		@event = Event.new
	end
	
	def show
		@event = Event.find(params[:id])
	end
	
	 def create
		 
		@event = Event.new
		@event.title = params[:title]
		@event.description = params[:description]
		@event.location = params[:location]
		@event.price = params[:price]
		@event.duration = params[:duration]
		@event.start_date = params[:start_date]
		@event.user = current_user
		@event.save
		
		if @event.save
			flash[:success] = "Tu as ajouter ton super potin."
			redirect_to root_path
			
		else render "new"

	end
	end
	
	   def authenticate_user
        unless current_user
            flash.now[:alert] = "Email ou mot de passe invalide"
            redirect_to new_user_session_path
        end
    end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def show

		@user = User.find(params[:id])

	end
	
	def authenticate_user
   unless current_user
      flash[:danger] = "Veuillez-vous connecter pour accéder au contenu."
   redirect_to new_user_session_path
    end
    end
	
	
def edit
	@user = User.find(params[:id])
end
	
	
def update
  @user = User.find(params[:id])
	user_params = params.require(:user).permit(:first_name, :last_name, :description)
	if @user.update(user_params)
		flash[:success] = "Ton profil est modifié"
    redirect_to user_path(:id => current_user.id)
  else
    render :edit
  end
end
	

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	def index
	end
	
	def secret
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_controller_helper.rb
module EventsControllerHelper
end

app/views/events/new.html.erb
<div class="body-dark">
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5 border-blue">
          <div class="card-body">
            <%= form_for @event do |f| %>  
              <% if @event.errors.any? %>
                <div class="alert alert-danger">
                    <div id="error_explanation">
                        <p> <%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</p>   
                 <ul><% @event.errors.full_messages.each do |message| %>
									 <li><%= message %></li>              
                      <% end %>
                 </ul>
                    </div>
                </div>
              <% end %>
 <h1 class="h3 mb-3 font-weight-normal text-center"> Créer un nouvel événement </h1>
     <div class="form-group">
      <%= f.label :title, "Titre" %>
      <em class="sm"></em> <br />
      <%= f.text_field :title, autocomplete: "title", class: "form-control" %>
     </div>
       <div class="form-group">
         <%= f.label :description, "Description" %><br />
         <%= f.text_field :description, autocomplete: "description", class: "form-control" %>
       </div>
    			<div class="form-group">
            <%= f.label :location, "Lieu" %><br />
            <%= f.text_field :location, autocomplete: "location", class: "form-control" %>
          </div>
             <div class="form-group">
                <%= f.label :price, "Prix" %><br />
                <%= f.number_field :price, autocomplete: "price", class: "form-control" %>
              </div>
              <div class="form-group">
                <%= f.label :start_date, "Date et heure" %>
                <%= f.datetime_field :start_date, autocomplete: "start_date", class: "form-control" %>

              </div>
              <div class="form-group">
                <%= f.label :duration, "Durée de l'événement" %><br />
                <%= f.number_field :duration, autocomplete: "duration", class: "form-control" %>
              </div>
              <div class="actions mt-5 mb-4">
                <%= f.submit "Créer un nouvel événement", class:"btn btn-md btn-dark btn-block text-uppercase" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<br><br><h1>Bienvenue sur la page de l'événement <%= @event.title%></h1><br>

<div class="body-dark">
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5 border-blue">
          <div class="card-body">
    <p>Titre de l'événement: <%= @event.title%></p>
<p>Description de l'événement: <%= @event.description%></p>
<p>Lieu : <%= @event.location%></p>
<p>Durée : <%= @event.duration%> min</p>
<p>Prix : <%= @event.price%> euros</p>
<p>Date : <%= @event.start_date%></p>
<p>Son administrateur : <%= @event.user.first_name%></p>
  </div>
</div>
</div>
		</div>
	</div>
</div>

<hr></hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		
    <title>Eventbrite-like</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
	<header><nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <a class="navbar-brand text-black"<%= link_to "Eventbrite-like", root_path, class: "nav-item nav-link active" %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <%= link_to "Home", root_path, class: "nav-item nav-link active" %>
			<%= link_to "New Events", new_event_path, class: "nav-item nav-link active" %>
	
			<a class="navbar-nav ml-auto">
        <% if current_user %>
          <li class="nav-item">  </li>
          <li class="nav-item">  <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class:"nav-link" %>
				  <li class="nav-item">  <%= link_to "Mon profil", user_path(:id => current_user.id), class:"nav-link" %></li>

        <% else %>
          <li class="nav-item"> <%= link_to "S'enregistrer", new_user_registration_path,   class:"nav-link" %> </li>
          <li class="nav-item"> <%= link_to "Se connecter", new_user_session_path, class:"nav-link" %> </li>
				<% end %> </a>
			  
    </div>
  </div>
</nav></header>
  <body>
		
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
<div class="body-blue">
 <div class="container">
   <div class="row">
     <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
       <div class="card card-signin my-5">
         <div class="card-body">
              <h1 class="h3 mb-3 font-weight-normal text-center">Complète ton profil</h1>
					 
					 	<div class="form-group">
							<label>Prénom</label>
							<%= f.text_field :first_name, class: 'form-control' %>
							<br>
  						<label>Nom</label>
							<%= f.text_field :last_name, class: 'form-control' %>
							<br>
	 						<label>Description</label>
							<%= f.text_area :description, class: 'form-control' %>
					 	</div>
					 	<div class="form-group">
						<div class="actions mt-5 mb-4">
                <%= f.submit "Enregistre", class:"btn btn-lg btn-dark btn-block text-uppercase" %>
              </div>
							<br><br>
							<%= link_to "Back", :back %>
					 	</div>
				 </div>
			 </div>
		 </div>
	 </div>
	</div>
</div>
	 

					 	<% end %>

app/views/users/show.html.erb
<br><br><h1>Bienvenue sur ta page <%= @user.first_name%></h1><br>

<div class="body-dark">
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5 border-blue">
          <div class="card-body">
    <p>Ton prénom: <%= @user.first_name%></p>
<p>Ton nom: <%= @user.last_name%></p>
<p>Ton email : <%= @user.email%></p>
<li class="nav-item"> <%= link_to "Modifie ton profil", edit_user_registration_path,   class:"nav-link" %> </li>
<li class="nav-item"> <%= link_to "Complète ton profil", edit_user_path,   class:"nav-link" %> </li>
  </div>
</div>
</div>
		</div>
	</div>
</div>

<hr></hr>

<h2>Tes événements</h2>

app/views/welcome/index.html.erb
<html><div class="jumbotron">
  <h1 class="display-4">Bienvenue</h1>
  <p class="lead"></p>
  <hr class="my-4">
  <p></p>

</div>
	
	<% Event.all.each do |event| %>


<div class="card">
  <div class="card-header">
    <%=  event.title%>
  </div><div class="card-body">
    <h5 class="card-title"><%= event.location %></h5>
    <p class="card-text"></p>
    <a class="btn btn-dark"<%= link_to "Détails de l'événement", event_path(event.id) %></a>
  </div>
</div>


<% end %>
</html>